configName: pic32mk_mcm_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK1024MCM100
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MK-MC_DFP\1.11.151
