configName: sam_9x60_curiosity
folderName: sam_9x60_curiosity
format_version: v1.0
frameworkPath: C:\h3
processor: SAM9X60D1G
projectName: sam_9x60_curiosity
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAM9X6_DFP\1.7.85
