configName: pic32mz_das_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MZ2064DAS169
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32MZ-DA_DFP\1.5.231
