package:
  format-version: "1.0.0"
  name: "bootloader_apps_uart"
  version: "v3.2.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "bootloader"
      type: "package"
      version: "dev"


