configName: sam_d21_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMD21J18A
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMD21_DFP\3.6.144
