configName: sam_a7g5_ek
folderName: sam_a7g5_ek
format_version: v1.0
frameworkPath: C:\h3
processor: SAMA7G54
projectName: sam_a7g5_ek
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMA7G5_DFP\1.2.178
