configName: sam_ha1_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMHA1G16AB
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMHA1_DFP\2.4.81
