configName: pic32ck_gc01_cult
folderName: pic32ck_gc01_cult
format_version: v1.0
frameworkPath: C:\Users\I76597\h3-BB
processor: PIC32CK2051GC01144
projectName: pic32ck_gc01_cult
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CK-GC_DFP\1.0.131
