configName: sam_a5d2_xult
folderName: sam_a5d2_xult
format_version: v1.0
frameworkPath: C:\h3
processor: ATSAMA5D27
projectName: sam_a5d2_xult
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMA5D2_DFP\1.9.106
