configName: wbz451_curiosity
folderName: wbz451_curiosity
format_version: v1.0
frameworkPath: C:\Users\I76597\h3-BB
processor: WBZ451
projectName: wbz451_curiosity
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-BZ_DFP\1.2.230
