configName: pic32cz_ca80_curiosity_ultra
folderName: pic32cz_ca80_curiosity_ultra
format_version: v1.0
frameworkPath: C:\Users\I76597\h3-BB
processor: PIC32CZ8110CA80208
projectName: pic32cz_ca80_curiosity_ultra
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CZ-CA80_DFP\1.2.150
