configName: sam_d11_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMD11D14AM
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMD11_DFP\2.6.76
