format_version: v1.0
configName: pic32cxbz_wbz45
folderName: pic32cxbz2_wbz45
frameworkPath: C:\Users\I76597\h3-BB
processor: WBZ451
projectName: pic32cxbz2_wbz45
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CX-BZ_DFP\1.2.230\WBZ451\atdf\WBZ451.atdf
